import { FormEndpoint, FormProps } from "./FormInterfaces";
import { ModalProps } from "../cc/Modal";
import React from "react";

export interface TableEndpoint {
  describeTable: string,
  loadTableData: string,
  saveRecord: string,
  deleteRecord: string,
}

export interface TableOrderBy {
  field: string,
  direction?: string | null
}

export interface TableColumns {
  [key: string]: any;
}

export interface TableInputs {
  [key: string]: any;
}

export type TableSelectionMode = '' | 'single' | 'multiple' | undefined | null;

export interface TablePermissions {
  canCreate?: boolean,
  canRead?: boolean,
  canUpdate?: boolean,
  canDelete?: boolean,
}

export interface TableUi {
  title?: string,
  subTitle?: string,
  addButtonText?: string,
  showHeader?: boolean,
  showFooter?: boolean,
  showFilter?: boolean,
  showSidebarFilter?: boolean,
  showHeaderTitle?: boolean,
  showNoDataAddButton?: boolean,
  showMoreActionsButton?: boolean,
  showAddButton?: boolean,
  showFulltextSearch?: boolean,
  showColumnSearch?: boolean,
  showAsPlainTable?: boolean,
  showInsertRow?: boolean,
  emptyMessage?: any,
  filters?: any,
  customFilters?: any,
  moreActions?: any,
  dataView?: any,
  orderBy?: TableOrderBy,
  selectionMode?: TableSelectionMode,
}

export interface TableDescription {
  columns: TableColumns,
  inputs: TableInputs,
  permissions?: TablePermissions,
  ui?: TableUi,
}

interface TableInvalidInput {
  name: string,
  id: number,
}

export interface TableData {
  current_page?: number,
  records: Array<any>,
  first_page_url?: string,
  from?: number,
  last_page_url?: string,
  last_page?: number,
  links?: Array<any>,
  next_page_url?: string|null,
  path?: string,
  per_page?: number,
  prev_page_url?: string|null,
  to?: number,
  total?: number,
  tree?: any,
}

export interface TableProps {
  componentName?: string,
  uid?: string,
  description?: TableDescription,
  descriptionSource?: 'props' | 'request' | 'both',
  recordId?: any,
  formDefaultValues?: any,
  formEndpoint?: FormEndpoint,
  formModalProps?: ModalProps,
  formProps?: FormProps,
  formActiveTabUid?: any,
  formReactComponent?: string,
  formCustomProps?: any,
  endpoint?: TableEndpoint,
  endpointParams?: any,
  model?: string,
  parentForm?: any,
  tag?: string,
  context?: string,
  where?: Array<any>,
  params?: any,
  page?: number,
  itemsPerPage?: number,
  inlineEditingEnabled?: boolean,
  isInlineEditing?: boolean,
  isUsedAsInput?: boolean,
  selectionMode?: TableSelectionMode,
  selection?: Array<any>,
  data?: TableData,
  async?: boolean,
  readonly?: boolean,
  closeFormAfterSave?: boolean,
  className?: string,
  fulltextSearch?: string,
  columnSearch?: any,
  filters?: any,
  view?: string,
  invalidInputs?: Array<TableInvalidInput>,
  crudController?: string,
  junctionTitle?: string,
  junctionModel?: string,
  junctionSourceColumn?: string,
  junctionDestinationColumn?: string,
  junctionSourceRecordId?: number,
  junctionSaveEndpoint?: string,
  formUrlSlug?: string,

  getEndpointParams?: (table: TableMeta) => object,
  getEndpointUrl?: (table: TableMeta, action: string) => string,
  getCsvImportEndpointParams?: (table: TableMeta) => any,
  getSelectionMode?: (table: TableMeta) => any,
  getRecordsToDisplay?: (table: TableMeta) => any,
  getFormProps?: (table: TableMeta) => any,
  getFormModalProps?: (table: TableMeta) => any,
  getCellClassName?: (table: TableMeta, columnName: string, column: any, rowData: any) => any,
  getCellCssStyle?: (table: TableMeta, columnName: string, column: any, rowData: any) => any,
  getMinColumnValue?: (table: TableMeta, columnName: string) => any,
  getMaxColumnValue?: (table: TableMeta, columnName: string) => any,
  getRowClassName?: (table: TableMeta, rowData: any) => any,

  renderAddButton?: (table: TableMeta) => any,
  renderMoreActionsButton?: (table: TableMeta) => any,
  renderHeaderButtons?: (table: TableMeta) => any,
  renderHeaderLeft?: (table: TableMeta) => any,
  renderFulltextSearch?: (table: TableMeta) => any,
  renderTitle?: (table: TableMeta) => any,
  renderHeaderRight?: (table: TableMeta) => any,
  renderHeader?: (table: TableMeta) => any,
  renderFilter?: (table: TableMeta) => any,
  renderSidebarFilter?: (table: TableMeta) => any,
  renderFooter?: (table: TableMeta) => any,
  renderDeleteConfirmModal?: (table: TableMeta) => any,
  renderFormModal?: (table: TableMeta) => any,
  renderForm?: (table: TableMeta) => any,
  renderCell?: (table: TableMeta, columnName: string, column: any, data: any, options: any) => any,
  renderInsertButton?: (table: TableMeta, row: any) => any,
  renderDeleteButton?: (table: TableMeta, row: any) => any,
  renderActionsColumn?: (table: TableMeta, row: any) => any,
  renderRecordsAsTree?: (table: TableMeta, nodes: any, idParent: number, level: number) => React.JSX.Element,
  renderRecords?: (table: TableMeta) => any,
  renderContent?: (table: TableMeta) => any,

  onAddClick?: (table: TableMeta) => void,
  onRowEdited?: (table: TableMeta, input: any, value: any) => void,
  onRowClick?: (table: TableMeta, row: any) => void,
  onPaginationChange?: (table: TableMeta, page: number, itemsPerPage: number) => void,
  onFilterChange?: (table: TableMeta, filterBy: any) => void,
  onOrderByChange?: (table: TableMeta, orderBy: TableOrderBy) => void,
  onAfterLoadData?: (table: TableMeta) => void,
  onAfterLoadDescription?: (table: TableMeta) => void,
}

export interface TableMeta {
  props: TableProps,

  endpoint, setEndpoint,
  activeRowId, setActiveRowId,
  async, setAsync,
  columnSearch, setColumnSearch,
  crudController, setCrudController,
  context, setContext,
  data, setData,
  description, setDescription,
  descriptionSource, setDescriptionSource,
  editMode, setEditMode,
  filterBy, setFilterBy,
  filters, setFilters,
  formActiveTabUid, setFormActiveTabUid,
  formEndpoint, setFormEndpoint,
  formProps, setFormProps,
  fulltextSearch, setFulltextSearch,
  inlineEditingEnabled, setInlineEditingEnabled,
  invalidInputs, setInvalidInputs,
  isInlineEditing, setIsInlineEditing,
  isUsedAsInput, setIsUsedAsInput,
  itemsPerPage, setItemsPerPage,
  loadingData, setLoadingData,
  model, setModel,
  page, setPage,
  readonly, setReadonly,
  formDefaultValues, setFormDefaultValues,
  recordId, setRecordId,
  recordNextId, setRecordNextId,
  recordPrevId, setRecordPrevId,
  recordSaveAfterOpen, setRecordSaveAfterOpen,
  rowToInsert, setRowToInsert,
  selection, setSelection,
  sidebarFilterHidden, setSidebarFilterHidden,
  tableUpdateIteration, setTableUpdateIteration,
  tag, setTag,
  uid, setUid,
  view, setView,

  getDefaultEndpointParams?: () => object,
  getDefaultEndpointUrl?: (action: string) => string,
  getDefaultCsvImportEndpointParams?: () => any,
  getDefaultSelectionMode?: () => any,
  getDefaultRecordsToDisplay?: () => any,
  getDefaultFormProps?: () => any,
  getDefaultFormModalProps?: () => any,
  getDefaultCellClassName?: (columnName: string, column: any, rowData: any) => any,
  getDefaultCellCssStyle?: (columnName: string, column: any, rowData: any) => any,
  getDefaultMinColumnValue?: (columnName: string) => any,
  getDefaultMaxColumnValue?: (columnName: string) => any,
  getDefaultRowClassName?: (rowData: any) => any,

  renderDefaultAddButton?: () => React.JSX.Element,
  renderDefaultMoreActionsButton?: () => React.JSX.Element,
  renderDefaultHeaderButtons?: () => React.JSX.Element,
  renderDefaultHeaderLeft?: () => React.JSX.Element,
  renderDefaultFulltextSearch?: () => React.JSX.Element,
  renderDefaultTitle?: () => React.JSX.Element,
  renderDefaultHeaderRight: () => React.JSX.Element,
  renderDefaultHeader: () => React.JSX.Element,
  renderDefaultFilter: () => React.JSX.Element,
  renderDefaultSidebarFilter: () => React.JSX.Element,
  renderDefaultFooter: () => React.JSX.Element,
  renderDefaultDeleteConfirmModal: () => React.JSX.Element,
  renderDefaultFormModal: () => React.JSX.Element,
  renderDefaultForm: () => React.JSX.Element,
  renderDefaultCell: (columnName: string, column: any, data: any, options: any) => React.JSX.Element,
  renderDefaultInsertButton: (row: any) => React.JSX.Element,
  renderDefaultDeleteButton: (row: any) => React.JSX.Element,
  renderDefaultActionsColumn: (row: any) => React.JSX.Element,
  renderDefaultRecordsAsTree: (nodes: any, idParent: number, level: number) => React.JSX.Element,
  renderDefaultRecords: () => React.JSX.Element,
  renderDefaultContent: () => React.JSX.Element,
}